-- MySQL Script generated by MySQL Workbench
-- Tue Oct  6 19:32:38 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tekzon_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tekzon_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tekzon_bd` DEFAULT CHARACTER SET utf8 ;
USE `tekzon_bd` ;

-- -----------------------------------------------------
-- Table `tekzon_bd`.`rol_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tekzon_bd`.`rol_usuario` ;

CREATE TABLE IF NOT EXISTS `tekzon_bd`.`rol_usuario` (
  `id_rolusuario` INT NOT NULL,
  `tipo_usuario` VARCHAR(45) NULL COMMENT 'Define el rol del usuario (administrador, tecnico o cajero)',
  PRIMARY KEY (`id_rolusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tekzon_bd`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tekzon_bd`.`usuario` ;

CREATE TABLE IF NOT EXISTS `tekzon_bd`.`usuario` (
  `id_usuario` INT NOT NULL,
  `id_rolusuario` INT NOT NULL,
  `nombre_usuario` VARCHAR(80) NULL COMMENT 'Nombre formal de la persona que se esta ingresando',
  `username` VARCHAR(80) NULL COMMENT 'El nombre de usuario del perfil o del rol',
  `contrasenia_usuario` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_rol_usuario_idx` (`id_rolusuario` ASC) ,
  CONSTRAINT `fk_usuario_rol_usuario`
    FOREIGN KEY (`id_rolusuario`)
    REFERENCES `tekzon_bd`.`rol_usuario` (`id_rolusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tekzon_bd`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tekzon_bd`.`cliente` ;

CREATE TABLE IF NOT EXISTS `tekzon_bd`.`cliente` (
  `cedula_cli` VARCHAR(20) NOT NULL,
  `nombre_cliente` VARCHAR(150) NULL,
  `apellido_cliente` VARCHAR(150) NULL,
  `telefono_cliente` VARCHAR(30) NULL,
  `direccion_cli` TEXT(180) NULL,
  PRIMARY KEY (`cedula_cli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tekzon_bd`.`dispositivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tekzon_bd`.`dispositivo` ;

CREATE TABLE IF NOT EXISTS `tekzon_bd`.`dispositivo` (
  `id_dispositivo` INT NOT NULL,
  `nombre_dis` VARCHAR(50) NULL,
  `marca` VARCHAR(50) NULL,
  `modelo` VARCHAR(50) NULL,
  `numero_serie` VARCHAR(100) NULL,
  `cedula_cli` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_dispositivo`),
  UNIQUE INDEX `numero_serie_UNIQUE` (`numero_serie` ASC) ,
  INDEX `fk_dispositivo_cliente1_idx` (`cedula_cli` ASC) ,
  CONSTRAINT `fk_dispositivo_cliente1`
    FOREIGN KEY (`cedula_cli`)
    REFERENCES `tekzon_bd`.`cliente` (`cedula_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tekzon_bd`.`orden_tecnico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tekzon_bd`.`orden_tecnico` ;

CREATE TABLE IF NOT EXISTS `tekzon_bd`.`orden_tecnico` (
  `id_ordentec` VARCHAR(30) NOT NULL,
  `id_dispositivo` INT NOT NULL,
  `id_usuario` INT NOT NULL COMMENT 'Segun el usuario, se especifica el nombre del tecnico',
  `falla_reportada` TEXT(220) NULL,
  `costo` DECIMAL(15,2) NULL,
  `estado` VARCHAR(30) NULL,
  `fecha_ingreso` DATE NULL,
  `fecha_entrega` DATE NULL,
  PRIMARY KEY (`id_ordentec`),
  INDEX `fk_orden_tecnico_dispositivo1_idx` (`id_dispositivo` ASC) ,
  INDEX `fk_orden_tecnico_usuario1_idx` (`id_usuario` ASC) ,
  CONSTRAINT `fk_orden_tecnico_dispositivo1`
    FOREIGN KEY (`id_dispositivo`)
    REFERENCES `tekzon_bd`.`dispositivo` (`id_dispositivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_tecnico_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tekzon_bd`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tekzon_bd`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tekzon_bd`.`categoria` ;

CREATE TABLE IF NOT EXISTS `tekzon_bd`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(50) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Baja logica: 1 = activa, 0 = inactiva',
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `nombre_categoria_UNIQUE` (`nombre_categoria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tekzon_bd`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tekzon_bd`.`producto` ;

CREATE TABLE IF NOT EXISTS `tekzon_bd`.`producto` (
  `cod_producto` VARCHAR(50) NOT NULL,
  `nombre_producto` VARCHAR(150) NULL,
  `precio_costo` DECIMAL(12,2) NULL,
  `precio_venta` DECIMAL(12,2) NULL,
  `existencia` INT NOT NULL DEFAULT 0 COMMENT 'Stock fisico real. Nace en 0 y solo lo altera el kardex o el ajuste de almacen',
  `stock_minimo` INT NOT NULL DEFAULT 0 COMMENT 'Umbral minimo de reposicion para alertas de stock bajo',
  `id_categoria` INT NULL,
  `marca` VARCHAR(50) NULL,
  `descripcion` TEXT NULL,
  `imagen` VARCHAR(255) NULL DEFAULT 'pantalla.jpg',
  `estado` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Baja logica: 1 = activo, 0 = inactivo',
  PRIMARY KEY (`cod_producto`),
  INDEX `idx_producto_estado_categoria` (`estado` ASC, `id_categoria` ASC) ,
  INDEX `fk_producto_categoria_idx` (`id_categoria` ASC) ,
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `tekzon_bd`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tekzon_bd`.`movimiento_inventario`
-- -----------------------------------------------------
-- Kádex transaccional del CRUD 3: registra cada Entrada, Salida o Ajuste
-- físico de existencias con su existencia previa y posterior calculada.
DROP TABLE IF EXISTS `tekzon_bd`.`movimiento_inventario` ;

CREATE TABLE IF NOT EXISTS `tekzon_bd`.`movimiento_inventario` (
  `id_movimiento` INT NOT NULL AUTO_INCREMENT,
  `cod_producto` VARCHAR(50) NOT NULL,
  `id_usuario` INT NOT NULL,
  `tipo_movimiento` VARCHAR(20) NOT NULL COMMENT 'ENTRADA: Compra/Devolucion, SALIDA: Merma/Uso, AJUSTE: Conteo fisico',
  `cantidad` INT NOT NULL COMMENT 'Cantidad de unidades afectadas',
  `existencia_previa` INT NOT NULL COMMENT 'Stock registrado antes de la operacion',
  `existencia_posterior` INT NOT NULL COMMENT 'Stock resultante tras la operacion',
  `motivo` VARCHAR(150) NOT NULL COMMENT 'Concepto o justificacion de la transaccion',
  `fecha_movimiento` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_movimiento`),
  INDEX `idx_movimiento_fecha_tipo` (`fecha_movimiento` ASC, `tipo_movimiento` ASC) ,
  INDEX `fk_movimiento_producto_idx` (`cod_producto` ASC) ,
  INDEX `fk_movimiento_usuario_idx` (`id_usuario` ASC) ,
  CONSTRAINT `fk_movimiento_producto`
    FOREIGN KEY (`cod_producto`)
    REFERENCES `tekzon_bd`.`producto` (`cod_producto`)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT `fk_movimiento_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tekzon_bd`.`usuario` (`id_usuario`)
    ON UPDATE CASCADE
    ON DELETE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tekzon_bd`.`detalle_orden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tekzon_bd`.`detalle_orden` ;

CREATE TABLE IF NOT EXISTS `tekzon_bd`.`detalle_orden` (
  `id_ordentec` VARCHAR(30) NOT NULL,
  `cod_producto` VARCHAR(50) NOT NULL,
  `cantidad` INT NULL,
  `precio_unitario` DECIMAL(12,2) NULL,
  PRIMARY KEY (`id_ordentec`, `cod_producto`),
  INDEX `fk_detalle_orden_producto1_idx` (`cod_producto` ASC) ,
  CONSTRAINT `fk_detalle_orden_producto1`
    FOREIGN KEY (`cod_producto`)
    REFERENCES `tekzon_bd`.`producto` (`cod_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tekzon_bd`.`venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tekzon_bd`.`venta` ;

CREATE TABLE IF NOT EXISTS `tekzon_bd`.`venta` (
  `num_factura` VARCHAR(50) NOT NULL,
  `cedula_cli` VARCHAR(20) NOT NULL,
  `monto_total` DECIMAL(12,2) NULL,
  `fecha_venta` DATE NULL,
  PRIMARY KEY (`num_factura`),
  INDEX `fk_venta_cliente1_idx` (`cedula_cli` ASC) ,
  CONSTRAINT `fk_venta_cliente1`
    FOREIGN KEY (`cedula_cli`)
    REFERENCES `tekzon_bd`.`cliente` (`cedula_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tekzon_bd`.`detalle_factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tekzon_bd`.`detalle_factura` ;

CREATE TABLE IF NOT EXISTS `tekzon_bd`.`detalle_factura` (
  `num_factura` VARCHAR(50) NOT NULL,
  `cod_producto` VARCHAR(50) NOT NULL,
  `cantidad` INT NULL,
  `Precio_unitario` DECIMAL(12,2) NULL,
  PRIMARY KEY (`num_factura`, `cod_producto`),
  INDEX `fk_detalle_factura_producto1_idx` (`cod_producto` ASC) ,
  CONSTRAINT `fk_detalle_factura_venta1`
    FOREIGN KEY (`num_factura`)
    REFERENCES `tekzon_bd`.`venta` (`num_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_factura_producto1`
    FOREIGN KEY (`cod_producto`)
    REFERENCES `tekzon_bd`.`producto` (`cod_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tekzon_bd`.`caja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tekzon_bd`.`caja` ;

CREATE TABLE IF NOT EXISTS `tekzon_bd`.`caja` (
  `id_caja` INT NOT NULL,
  `monto_apertura` DECIMAL(12,2) NULL,
  `monto_cierre` DECIMAL(12,2) NULL,
  `estado` VARCHAR(60) NULL,
  `fecha_apertura` DATE NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_caja`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) ,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tekzon_bd`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tekzon_bd`.`pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tekzon_bd`.`pago` ;

CREATE TABLE IF NOT EXISTS `tekzon_bd`.`pago` (
  `id_pago` INT NOT NULL,
  `id_caja` INT NOT NULL,
  `tipo_origen` VARCHAR(30) NULL,
  `metodo_pago` VARCHAR(50) NULL,
  `monto_usd` DECIMAL(12,2) NULL,
  `tasa_cambio` DECIMAL(12,2) NULL,
  `referencia` VARCHAR(100) NULL,
  `fecha_pago` DATE NULL,
  `venta_num_factura` VARCHAR(50) NOT NULL,
  `id_ordentec` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_pago`),
  INDEX `fk_pago_caja1_idx` (`id_caja` ASC) ,
  INDEX `fk_pago_venta1_idx` (`venta_num_factura` ASC) ,
  INDEX `fk_pago_orden_tecnico1_idx` (`id_ordentec` ASC) ,
  CONSTRAINT `fk_pago_caja1`
    FOREIGN KEY (`id_caja`)
    REFERENCES `tekzon_bd`.`caja` (`id_caja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_venta1`
    FOREIGN KEY (`venta_num_factura`)
    REFERENCES `tekzon_bd`.`venta` (`num_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_orden_tecnico1`
    FOREIGN KEY (`id_ordentec`)
    REFERENCES `tekzon_bd`.`orden_tecnico` (`id_ordentec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tekzon_bd`.`tasa_cambio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tekzon_bd`.`tasa_cambio` ;

CREATE TABLE IF NOT EXISTS `tekzon_bd`.`tasa_cambio` (
  `id_tasa` INT NOT NULL,
  `tasa_num` DECIMAL(15,4) NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id_tasa`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
